apiVersion: apps/v1
kind: Deployment
metadata:
  name: networkcguckcoffee-deployoment
  labels:
    app: nccoffee
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nccoffee
  template:
    metadata:
      labels:
        app: nccoffee
    spec:
      containers:
        - name: nccoffee
          image: thenetworkchuck/nccoffee:pourover
          imagePullPolicy: Always
          ports:
          - containerPort: 80
